### ISSUE TITLE
Can't Turn on Video on MAC Application

### ISSUE THREAD

**Issue by vijayamin83** [aws-samples/amazon-chime-sdk-classroom-demo#4] opened 2020-04-17 04:05 UTC
I have successfully deployed the application to the AWS and when I install the /release/app.dmg, it's successfully installed the app in my MacBook.

Also, I can open it and join as teacher or student, but can't turn on the video option.

**Comment by simmkyu** [comment] 2020-04-17 22:10
1. Could you make sure you have clicked "OK" in the video permission dialog upon the first launch? The video permission dialog will appear when you click the video icon at the bottom.

<img width="560" alt="1" src="https://user-images.githubusercontent.com/36240708/79617308-02f46700-80bc-11ea-98dc-dbc6b1cfac28.png">


2. Make sure you have the name of your video device at the top-right corner. In my MacBook Pro without any external cameras, "FaceTime HD Camera" has been selected as default.

<img width="600" alt="2" src="https://user-images.githubusercontent.com/36240708/79617319-0687ee00-80bc-11ea-8c25-febf0737ba69.png">


3. If you still can't see your video, please open "View => Toggle Developer Tools" and check if you see any warning or error message. You can share error messages in this issue too.

<img width="600" alt="3" src="https://user-images.githubusercontent.com/36240708/79617322-0851b180-80bc-11ea-8d79-1e20b779b451.png">

**Comment by vijayamin83** [comment] 2020-04-20 04:43
Thank You for the reverting back.

Unfortunately, I am not getting any alerts like this to allow the video permissions. I have also checked the system settings and from privacy settings, I have enabled the video manually. But still there is the same problem.

Note. I am using Mac Catalina OS latest one.

**Comment by vijayamin83** [comment] 2020-04-20 07:20
I have deployed the code through the cloud9 service also. But it's also not working even after I got the successfully message.

https://ilaetvwm1g.execute-api.us-east-1.amazonaws.com/Prod/

**Comment by simmkyu** [comment] 2020-04-20 23:27
@vijayamin83 I removed your demo URL from the comment above and the revision history. If others download your app and use it, you might be charged. To fully remove the URL and associated resources, go to CloudFormation and delete the stack.

In Security & Privacy, make sure you have enabled a checkbox for *Camera* and *Microphone*.
<img width="500" alt="Screen Shot 2020-04-20 at 4 13 37 PM" src="https://user-images.githubusercontent.com/36240708/79808218-01c47380-8322-11ea-82dc-0f3b49da177a.png">

For debugging:

<img width="500" alt="Screen Shot 2020-04-20 at 4 19 25 PM" src="https://user-images.githubusercontent.com/36240708/79808766-aa270780-8323-11ea-93f0-2832bbae749f.png">

1. Start your Classroom app.
2. Please click "View => Toggle Developer Tools". Logs will appear at the bottom.
3. Join a meeting and click the video icon to turn your webcam on.
3. Share log messages at the bottom. (Copy and paste all log messages to `.txt` file, zip it, and attach it in this issue. Logs only contain meeting ID and attendee ID.)

**Comment by vijayamin83** [comment] 2020-04-21 13:36
I have removed the Stacks and everything. Re setup the things, but still getting the same issue. Actually, I am not getting the camera permission for the application in the MAC settings:

See the screen shots:

![image](https://user-images.githubusercontent.com/468540/79872119-fbf28f00-8402-11ea-978f-3e205863d58d.png)

![image](https://user-images.githubusercontent.com/468540/79872186-13ca1300-8403-11ea-918f-1b6310f0cbe8.png)

**Comment by vijayamin83** [comment] 2020-04-24 05:41
Any Update?

**Comment by simmkyu** [comment] 2020-04-24 06:21
When the FaceTime camera on my MacBook (Mojave) stopped working, I ran the following command in the Terminal app to reset my camera:
```
sudo killall VDCAssistant
```

Could you also share your Classroom demo logs by following these steps? I wonder if SDK throws any specific error messages.

1. Start your Classroom app.
1. Please click "View => Toggle Developer Tools". Logs will appear at the bottom.
1. Join a meeting and click the video icon to turn your webcam on.
1. Share log messages at the bottom. (Copy and paste all log messages to .txt file, zip it, and attach it in this issue. Logs only contain meeting ID and attendee ID.)

<img width="500" alt="Screen Shot 2020-04-20 at 4 19 25 PM" src="https://user-images.githubusercontent.com/36240708/79808766-aa270780-8323-11ea-93f0-2832bbae749f.png">

**Comment by vijayamin83** [comment] 2020-04-26 16:21
so Here I have attached the log.

Note that when I run the command "yarn dev" I am able to see the video, but when I build the app with the deploy command as per README file, it's not working. 

[1587917839870.log.zip](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/files/4535879/1587917839870.log.zip)

**Comment by simmkyu** [comment] 2020-04-27 22:34
```
2020-04-26T16:15:47.743Z [ERROR] SDK - failed to get video device for constraints
{"video":{"deviceId":{"exact":"e6e2713277b5db68eff359f515f56de688d4b9e296bf1a7347b396ba83cbcf54"},"width":960,"height":540,"frameRate":15}}:
Could not start video source
2020-04-26T16:15:47.750Z [ERROR] SDK - no video device chosen, stopping local video tile
2020-04-26T16:15:47.755Z [WARN] SDK - could not acquire video input from current device
```

When you call `chooseVideoInputDevice`, Chime SDK invokes [`navigator.mediaDevices.getUserMedia()` in Web API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) that asks for the camera permission and returns the camera's MediaStream object if you allowed. In the attached log, the `getUserMedia()` API throws the `Could not start video source` error (NotReadableError).

Searching `NotReadableError: Could not start video source` online... This error can happen if:
- another application is using the camera, or
- OS or other applications are preventing the camera access, or
- the hardware is having an issue.

**Comment by vijayamin83** [comment] 2020-04-28 09:29
I have tried all possible solutions as above. Downloaded application does not ask for the Camera permissions at all. So, video is not working.

Screen sharing is working properly
Note: 
1 Downloaded application does not work in the other MAC also
2 application run with "yarn dev" is working fine.
3 Even in the window system it is not working.

Thanks.

**Comment by vijayamin83** [comment] 2020-05-23 09:23
Can you change the design when screen share option is enabled. Just like other meeting app?

So, user can view just the stop button at the top of the screen

**Comment by aburnson** [comment] 2020-06-01 19:19
Unfortunately there doesn't appear to be anything we can do in this demo to resolve the camera issue you are experiencing. According to the logs, the application is unable to access the selected device due to some kind of system-level restriction. Usually this is because of a privacy setting, but as @simmkyu there could be other causes as well.

Closing this issue for now. We can re-open this if we later find there is some way to control this behavior from the application or if we can reproduce this.

> Can you change the design when screen share option is enabled. Just like other meeting app?
> So, user can view just the stop button at the top of the screen

Could you open a [new issue](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/issues/new) for this feature request and provide a little bit more detail on the current behavior compared to the behavior you expect?

**Closed by aburnson** 2020-06-01 19:19 UTC

**Comment by walfen** [comment] 2020-06-05 13:20
I'm having the same error with Xiaomi Redmi 4X and Android 7.1.2.

`2020-06-05T11:14:39.191Z [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"6b617456ca056c31ab3ec94ca1a1ca8713425a64bda50f040e84a9f7aa43f3a3"},"width":960,"height":540,"frameRate":15}}: Could not start video source`

**Comment by vijayamin83** [comment] 2020-06-18 07:31
Nevermind, I have fixed this issue at my end. You need to make the changes in the .plist file

**Comment by shriyajuneja** [comment] 2021-03-17 13:49
> I'm having the same error with Xiaomi Redmi 4X and Android 7.1.2.
> 
> `2020-06-05T11:14:39.191Z [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId": "exact":"6b617456ca056c31ab3ec94ca1a1ca8713425a64bda50f040e84a9f7aa43f3a3"},"width":960,"height":540,"frameRate":15}}: Could not start video source`

@walfen were you able to figure this out ?
